minor updates

diff --git a/bin/games b/bin/games
--- a/bin/games
+++ b/bin/games
@@ -2,9 +2,6 @@
 
 GAME_LOCATION=${GAME_LOCATION:-$HOME/media/games}
 
-## For Torchlight
-export SDL_VIDEO_X11_XINERAMA=0
-export SDL_VIDEO_X11_XRANDR=0
 export JAVA_EXEC=`which java`
 
 GAME=
@@ -12,14 +9,14 @@ BIN=
 FLAGS=
 
 case $1 in
-df)	GAME="df_linux"		BIN="df" ;;
-eu)	GAME="EufloriaHD"	BIN="EufloriaHD.bin.x86_64" ;;
+df)		GAME="df_linux"		BIN="df" ;;
+eu)		GAME="EufloriaHD"	BIN="EufloriaHD.bin.x86_64" ;;
 ftl)	GAME="FTL"		BIN="FTL" ;;
 ksp)	GAME="KSP_linux"	BIN="KSP.x86_64" ;;
 splice) GAME="Splice"		BIN="Splice.x86_64" ;;
 sudoku)	exec ksudoku ;;
 uplink)	GAME="uplink"	FLAGS="-graphics_fullscreen" BIN="uplink.bin.x86" ;;
-*)	echo "Game not found \"$1\"" && exit 1 ;;
+*)		echo "Game not found \"$1\"" && exit 1 ;;
 esac
 
 [[ ! -d $GAME_LOCATION/$GAME ]] && exit 1
